const express = require("express");
const router = express.Router();
const couponController = require("../controllers/coupon.controller");
router.get("/",couponController.getAll);
router.post("/check",couponController.check);
router.get("/:code",couponController.get);
router.post("/",couponController.post);
router.put("/",couponController.put);
router.delete("/:code",couponController.delete);
module.exports = router;